-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Ciudad"
(
    "Id_ciudad" integer NOT NULL,
    "Ciudad" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Departamento" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Postal_code" integer NOT NULL,
    CONSTRAINT "Ciudad_pkey" PRIMARY KEY ("Id_ciudad")
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    "Id_Cliente" integer NOT NULL,
    "Id_Persona" integer NOT NULL,
    "Fecha_Ingreso" time(6) without time zone NOT NULL,
    "Calificacion" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Estado" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Cliente_pkey" PRIMARY KEY ("Id_Cliente")
);

CREATE TABLE IF NOT EXISTS public."Cuentas"
(
    "Id_Cuentas" integer NOT NULL,
    "Id_Cliente" integer NOT NULL,
    "Nro_cuenta" date NOT NULL,
    "Fecha_Alta" time(6) without time zone NOT NULL,
    "Tipo_cuenta" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Estado" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Saldo" integer NOT NULL,
    "Nro_contrato" integer NOT NULL,
    "Costo_Mantenimiento" integer NOT NULL,
    "Promedio_Acreditacion" integer NOT NULL,
    "Moneda" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Cuentas_pkey" PRIMARY KEY ("Id_Cuentas")
);

CREATE TABLE IF NOT EXISTS public."Movimientos"
(
    "Id_Movimiento" integer NOT NULL,
    "Id_Cuentas" integer NOT NULL,
    "Fecha_movimiento" time(6) without time zone NOT NULL,
    "Tipo_movimiento" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Saldo_anterior" integer NOT NULL,
    "Saldo_actual" integer NOT NULL,
    "Monto_movimiento" integer NOT NULL,
    "Cuenta_origen" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Cuenta_destino" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    "Canal" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Movimientos_pkey" PRIMARY KEY ("Id_Movimiento")
);

CREATE TABLE IF NOT EXISTS public."Persona"
(
    "Id_Persona" integer NOT NULL,
    "Id_Ciudad" integer NOT NULL,
    "Nombre" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Apellido" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Tipodocumento" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Nrodocumento" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Direccion" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Celular" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Estado" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Persona_pkey" PRIMARY KEY ("Id_Persona")
);

ALTER TABLE IF EXISTS public."Cliente"
    ADD FOREIGN KEY ("Id_Persona")
    REFERENCES public."Persona" ("Id_Persona") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cuentas"
    ADD FOREIGN KEY ("Id_Cliente")
    REFERENCES public."Cliente" ("Id_Cliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Movimientos"
    ADD FOREIGN KEY ("Id_Cuentas")
    REFERENCES public."Cuentas" ("Id_Cuentas") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Persona"
    ADD FOREIGN KEY ("Id_Ciudad")
    REFERENCES public."Ciudad" ("Id_ciudad") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;